on:
  schedule:
    - cron: "10-14 * * * "

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run a script
        run: echo "This job runs every minute from 8 to 11 seconds past the minute."
